// Generated by CoffeeScript 1.8.0
(function() {
  '(function(d, s, id) {\n  var js, fjs = d.getElementsByTagName(s)[0];\n  if (d.getElementById(id)) return;\n  js = d.createElement(s); js.id = id;\n  js.src = "http//connect.facebook.net/ko_KR/sdk.js#xfbml=1&appId=1501811433375013&version=v2.0";\n  fjs.parentNode.insertBefore(js, fjs);\n}(document, \'script\', \'facebook-jssdk\'));';


}).call(this);
