// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    $("#logo").css("padding-top", Math.floor($(window).height() / 2 - $(window).height() / 3)).css("padding-bottom", Math.floor($(window).height() / 2 + 10));
    $("html, head").scrollTop(0);
  });

}).call(this);
